		<div id="ygma">
			<div id="ygmaheader">
				<div class="bd sp">
					<div id="ymenu" class="ygmaclr">
						<div id="yahoo" class="ygmaclr">
							<div id="ygmabot">
								<h1 class="hd">Curriculum Central Answers!</h1>
							</div>
						</div>
					</div>
				</div>
			</div> <!-- ygmaheader -->

			<div id="yan-header-searchbox">
				<form method="get" action="">
					<div>
						<input id="yan-p" class="textfield default" name="p" size="40" value="" type="text">
						<span class="cta">
							<button class="cta-button secondary" name="submit-go" value="Search CC FAQs" id="">
								<span>
									<span>
										<span>
											<span>Search CC FAQs</span>
										</span>
									</span>
								</span>
							</button>
						</span>
						<a href="../index.jsp" id="ask-a-question">Back to CC</a>
						<a href="index.jsp" id="ask-a-question">CC FAQs</a>
						<a href="ask.jsp" id="ask-a-question">Ask a Question</a>
						<a href="" id="advanced-search">Advanced Search</a>
					</div>
				</form>
			</div>
		</div> <!-- ygma -->